### PR TITLE
jsayers edits/suggestions

### PR DESCRIPTION
**Pull request by j-sayers**
I only just started looking over this but have opened a pull request so that I can add comments.

No need to merge this yet as I'll be adding to it.

### CODE REVIEW

**Comment by j-sayers** [comment]
General comment: there is a lot of overlap between the readme and the "getting started" files. in fact package installation is addressed in the readme and "getting started" picks up from there. 

Maybe the readme should just have a very brief introduction about what motus is and then all subsequent stuff about package installation etc should be moved over into "getting started".

"readme" files often serve as a primary guide, but in the github universe they are really just the default landing page and could have little more than a logo and table of contents if we wanted. Might be worth putting the important stuff in "getting started"

**Comment by j-sayers** [comment]
@steffilazerte I'm not sure how much I should be commenting vs modifying. For instance, I think most of what is in the readme file should be place in "getting started" so that the first steps are all in one place. And the "reference" menu should probably refer just to "functions". Should I change that sort of stuff and allow you to sift through the proposed changes? Or just comment? I'm not sure what's most efficient or preferred. I'm also keeping in mind that I'm just the first reviewer here so opinions may differ...

**Comment by j-sayers** [comment]
Another general comment: the move to this format — which I think is definitely for the best and is well worth it for many reasons — has the risk of making access more difficult for the casual participant.

As it stands, the only way to get access to in-depth data is through the R package, so anyone who wants to dig deeper than the daily summaries needs to use the R package.

That's not a problem, but it does mean we serve a broader and more diverse audience than most R packages do.

So we probably need more theory in the docs than we'd normally expect: how each function's arguments relate to the overall data structure.

This is just a placeholder comment. The new format is great and pretty clearly the way to go forward. But motus is an odd (and very special) duck, so our version of docs may look a tad different from the usual.

**Comment by steffilazerte** [comment]
Hi @j-sayers

1. For big/general stuff, make comments and I can address them. Some of the comments you've made reflect more pkgdown settings, so it's probably not worth your time figureing out the pkgdown package just to give feedback. 

On that note, perhaps a better way for you to comment, might be to "Review" my Pull request. You can [show all changed files and filter to just RMD](https://github.com/MotusWTS/motus/pull/12/files?file-filters%5B%5D=.Rmd&show-deleted-files=true&show-viewed-files=true) and you can leave comments line by line or on whole sections. You can also add suggestions to you comments if they're easy fixes, but I'm happy to make changes. That will give me a checklist of comments to make sure I resolve.

2. > I'm also keeping in mind that I'm just the first reviewer here so opinions may differ...

For the most part you're the *only* reviewer, so let's go with your opinions unless I feel strongly different, and then we can discuss :grin:

3. 
> Another general comment: the move to this format — which I think is definitely for the best and is well worth it for many reasons — has the risk of making access more difficult for the casual participant.
> 
> As it stands, the only way to get access to in-depth data is through the R package, so anyone who wants to dig deeper than the daily summaries needs to use the R package.

I'm not sure I understand exactly. I understand that many motus users aren't necessarily hard-core R users (I get that kind of thing a lot with my [weathercan](https://github.com/ropensci/weathercan) package). But I don't understand how moving content from book format to website format has changed how users access the data?

Do you mean more that the format change makes the documentation more intimidating to the casual user? That's a good point to consider and I think your ideas for revamping the README/home page could be a good way of addressing this. 

> So we probably need more theory in the docs than we'd normally expect: how each function's arguments relate to the overall data structure.

Do you mean in the function reference or in the articles? Function references are the same help pages from R package, so we can clarify them, definitely, but don't want to get too carried away. However, in the articles we should definitely be explicit. Feel free to note places where you think we can be more helpful to the user! Also, I have a couple of new/revamped articles about understanding Motus data, which might be useful if tweaked or referenced earlier on. 

Thanks for the feedback! I'm really glad to be getting the comments from different perspectives. Keep it coming :grin:

**Comment by j-sayers** [comment]
> > Another general comment: the move to this format — which I think is definitely for the best and is well worth it for many reasons — has the risk of making access more difficult for the casual participant.
> > As it stands, the only way to get access to in-depth data is through the R package, so anyone who wants to dig deeper than the daily summaries needs to use the R package.
> 
> I'm not sure I understand exactly. I understand that many motus users aren't necessarily hard-core R users (I get that kind of thing a lot with my [weathercan](https://github.com/ropensci/weathercan) package). But I don't understand how moving content from book format to website format has changed how users access the data?
> 
> Do you mean more that the format change makes the documentation more intimidating to the casual user? That's a good point to consider and I think your ideas for revamping the README/home page could be a good way of addressing this.
> 
> > So we probably need more theory in the docs than we'd normally expect: how each function's arguments relate to the overall data structure.
> 
> Do you mean in the function reference or in the articles? Function references are the same help pages from R package, so we can clarify them, definitely, but don't want to get too carried away. However, in the articles we should definitely be explicit. Feel free to note places where you think we can be more helpful to the user! Also, I have a couple of new/revamped articles about understanding Motus data, which might be useful if tweaked or referenced earlier on.
> 

Sorry that wasn't really clear. The old R Book included a lot more theory in addition to how to use the functions. Some of that is still front and centre (Birds Eye view of Motus) but the new docs are quite pared down in terms of content. The old book is still there in extra articles, but there's a risk of fragmenting the information too much between different articles. I understand that for a variety of reasons we want to keep the old book accessible in its current form. But maybe more of the content should be migrated over into the new docs...? I don't have any clear idea myself, just thinking aloud more than anything...

**Comment by j-sayers** [comment]
@steffilazerte I think I'm done for now, especially with Amie still making a few changes to the articles. 

Reordering the sections address most of my comments! (I actually just rolled back my earlier edits for that reason.) I did move some of troubleshooting around but that's it for now. 

- One suggestion: Can you move Articles in the navbar, to after Getting Started and before Troubleshooting?

- Second navbar suggestion: is it possible to set visibility to persistent, so that you can always see the navigation / content outline without having to scroll up first?

- Just realized we missed the "Reference" link on the navbar, containing Understanding Motus Data and Database Variables.

**Comment by steffilazerte** [comment]
Hi @j-sayers 

1. Yes, definitely 
2. I can look into this, I think probably, but no promises :grin:
3. There is a References section in the [Articles](https://motuswts.github.io/motus/articles/index.html) list, but if I understand correctly, you don't want it in the Articles? You want it as another Nav bar item? Is the Reference section something we want people to look at right off the bat? If so then yes, I can put it in the Nav bar, but if not, I suggest leaving it in the Articles, so that it's something people see when they're ready to look at more detailed content.

**Comment by j-sayers** [comment]
2. yeah a bit of a niggle to be honest. It's just nice to have some context of the structure, and where to go to find things, at a glance. Not to mention the search bar always vanishes unless the user scrolls up again.

3. Good point. trade-off between people clicking on it prematurely or not finding it easily... I think it was discussed whether to convert the Articles dropdown to a link to the Articles page. Maybe that's the best balance?

**Comment by steffilazerte** [comment]
Okay, I added these edits by hand, and fixed the navbar order. I'm going to leave the references in the articles list, as I think there are enough ways that people can find them without making the navbar too busy. Unfortunately I'm also going to leave the navbar position alone as I think with the way pkgdown works, that might be overly tricky/fragile to tweak. I'll keep an eye out for examples, though.

**Pull request closed without merging**
